<a href="https://colab.research.google.com/github/tharak-bairneni/numpy-classroom-assignment/blob/main/numpy_scores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#===================================
#✅ TASK 1 — Generate & Inspect Data
#===================================

import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate random scores (5 students, 4 subjects)
scores = np.random.randint(50, 101, size=(5, 4))

print("Scores:\n", scores)

# 3rd student, 2nd subject (index 2,1)
print("\n3rd student, 2nd subject:",
      scores[2, 1])

# Last 2 students (all subjects)
print("\nLast 2 students:\n",
      scores[-2:, :])

# First 3 students, subjects 2 and 3
print("\nFirst 3 students, subjects 2 & 3:\n",
      scores[:3, 1:3])

Scores:
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]
 [71 51 73 93]]

3rd student, 2nd subject: 60

Last 2 students:
 [[85 89 73 52]
 [71 51 73 93]]

First 3 students, subjects 2 & 3:
 [[78 64]
 [70 88]
 [60 60]]


In [2]:
#===================================
#✅ TASK 2 — Analysis with Broadcasting
#===================================



 # Column-wise mean (average per subject)
column_mean = np.round(np.mean(scores, axis=0), 2)
print("\nColumn-wise mean:", column_mean)

# Add curve using broadcasting
curve = np.array([5, 3, 7, 2])

curved_scores = scores + curve

# Ensure no value exceeds 100
curved_scores = np.clip(curved_scores, None, 100)

print("\nCurved Scores:\n", curved_scores)

# Row-wise max (best subject per student)
row_max = np.max(curved_scores, axis=1)
print("\nBest score per student:", row_max)


Column-wise mean: [74.6 69.6 71.6 75.6]

Curved Scores:
 [[93 81 71 94]
 [62 73 95 70]
 [77 63 67 75]
 [90 92 80 54]
 [76 54 80 95]]

Best score per student: [94 95 77 92 95]


In [3]:
#===================================
#✅ TASK 3 — Normalize & Identify
#===================================

# Min-max normalization per row
row_min = np.min(curved_scores, axis=1, keepdims=True)
row_max = np.max(curved_scores, axis=1, keepdims=True)

normalized = (curved_scores - row_min) / (row_max - row_min)

print("\nNormalized Scores:\n", normalized)

# Find highest value in normalized array
max_index = np.unravel_index(np.argmax(normalized), normalized.shape)

print("\nHighest normalized value at:")
print("Student index:", max_index[0])
print("Subject index:", max_index[1])

# Extract scores strictly above 90
above_90 = curved_scores[curved_scores > 90]

print("\nScores above 90:", above_90)


Normalized Scores:
 [[0.95652174 0.43478261 0.         1.        ]
 [0.         0.33333333 1.         0.24242424]
 [1.         0.         0.28571429 0.85714286]
 [0.94736842 1.         0.68421053 0.        ]
 [0.53658537 0.         0.63414634 1.        ]]

Highest normalized value at:
Student index: 0
Subject index: 3

Scores above 90: [93 94 95 92 95]
